CREATE TABLE TIPO_CAMBIO {
	ID INT(10),
	MONEDA_ORIGEN VARCHAR(10),
	MONEDA_DESTINO VARCHAR(10),
	TIPO_CAMBIO DOUBLE, 
	FECHA DATE
};

INSERT INTO TIPO_CAMBIO (MONEDA_ORIGEN, MONEDA_DESTINO, TIPO_CAMBIO, FECHA) VALUES('USD', 'PEN', 3.6, '01/03/2012');